/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package au.com.rakesh.crawler.rest;

import org.springframework.http.ResponseEntity;

import au.com.rakesh.crawler.model.PageTreeInfo;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-02T22:39:21.740Z")

@Api(value = "crawler", description = "the crawler API")
public interface CrawlerApi {

    @ApiOperation(value = "Get the web page tree info upto certain depth", notes = "", response = PageTreeInfo.class, authorizations = {
            @Authorization(value = "basicAuth") }, tags = { "web-crawler", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation", response = PageTreeInfo.class),
            @ApiResponse(code = 400, message = "Invalid page url", response = Void.class),
            @ApiResponse(code = 401, message = "Unauthorized to use the service", response = Void.class),
            @ApiResponse(code = 404, message = "Page not found", response = Void.class) })

    ResponseEntity<PageTreeInfo> getWebPageTreeInfo(
            @ApiParam(value = "Url of the webpage for getting tree info", required = true) String url,
            @ApiParam(value = "Desired depth for crawling") Integer depth);

}
